<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputPath>../addons/counterstrikesharp/plugins/MenuManagerCore</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.369" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.8" />
    <Reference Include="PlayerSettingsApi"><HintPath>..\PlayerSettingsApi.dll</HintPath></Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MenuManagerApi\MenuManagerApi.csproj" />
  </ItemGroup>

</Project>
