name: MenuManager build and release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      
      - name: Restore dependencies
        run: |
          dotnet restore MenuManagerApi/MenuManagerApi.csproj
          dotnet restore MenuManagerCore/MenuManagerCore.csproj
      
      - name: Build MenuManagerApi
        run: dotnet build MenuManagerApi/MenuManagerApi.csproj -c Release --no-restore
      
      - name: Build MenuManagerCore
        run: dotnet build MenuManagerCore/MenuManagerCore.csproj -c Release --no-restore

      - name: Create release asset
        if: github.event_name == 'release'
        run: zip -r MenuManagerCore-${{ github.event.release.tag_name }}.zip ./addons/

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./MenuManagerCore-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
